name: pr

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn zip
